export default[
    {
        userName: "rajwi.mdr",
        time: "1h",
        profileImg: "./images/raabi.jpeg",
        likes: "500",
        comments: "213",
        caption: "I am the Best !",
        hero: "./images/raabi.jpeg",
    },
    {
        userName: "routineofnepalronb",
        time: "3h",
        profileImg: "./images/juice.jpg",
        likes: "3,793",
        comments: "18",
        caption: "Amazing: Shah Rukh Khan becomes the most popular Bollywood Actor in 2023, accordng to the IMDB's top 10 list.",
        hero: "./images/juice.jpg",
    },
    {
        userName: "Shreejal27",
        time: "3h",
        profileImg: "./images/juice.jpg",
        likes: "1,000",
        comments: "99",
        caption: "Hello World",
        hero: "./images/juice.jpg",
    },
    {
        userName: "Shreejal27",
        time: "3h",
        profileImg: "./images/juice.jpg",
        likes: "1,000",
        comments: "99",
        caption: "Hello World",
        hero: "./images/juice.jpg",
    },
    {
        userName: "Shreejal27",
        time: "3h",
        profileImg: "./images/juice.jpg",
        likes: "1,000",
        comments: "99",
        caption: "Hello World",
        hero: "./images/juice.jpg",
    },
    {
        userName: "Shreejal27",
        time: "3h",
        profileImg: "./images/juice.jpg",
        likes: "1,000",
        comments: "99",
        caption: "Hello World",
        hero: "./images/juice.jpg",
    },
]