export default[
    {
        userName: "_rajwiii",
        time: "7 s",
        profileImg: "./images/post/profilePic/raabu.jpg",
        likes: "420",
        comments: "213",
        caption: "Let's go below zero and hide from the sun I love you forever where we'll have some fun",
        hero: "./images/post/hero/r.jpg",
        verified: true,
    },
    {
        userName: "__yaankaa",
        time: "10 m",
        profileImg: "./images/post/profilePic/ja.jpg",
        likes: "420",
        comments: "33",
        caption: "what is this?",
        hero: "./images/post/hero/ja.jpg",
        verified: true,
    },
    {
        userName: "leexon_xhrextha",
        time: "10 m",
        profileImg: "./images/post/profilePic/l.jpg",
        likes: "69",
        comments: "13",
        caption: "ululululu",
        hero: "./images/post/hero/l.jpg",
        verified: true,
    },
    {
        userName: "_rajwiii",
        time: "94 w",
        profileImg: "./images/post/profilePic/raabu.jpg",
        likes: "420",
        comments: "213",
        caption: "Let's go below zero and hide from the sun I love you forever where we'll have some fun",
        hero: "./images/post/hero/r.jpg",
        verified: true,
    },
    {
        userName: "routineofnepalronb",
        time: "3 h",
        profileImg: "./images/juice.jpg",
        likes: "3,793",
        comments: "18",
        caption: "Amazing: Shah Rukh Khan becomes the most popular Bollywood Actor in 2023, accordng to the IMDB's top 10 list.",
        hero: "./images/juice.jpg",
        verified: false,
    },
    {
        userName: "Shreejal27",
        time: "3 h",
        profileImg: "./images/juice.jpg",
        likes: "1,000",
        comments: "99",
        caption: "Hello World",
        hero: "./images/juice.jpg",
        verified: false,
    },
    {
        userName: "rap",
        time: "2 d",
        profileImg: "./images/juice.jpg",
        likes: "1,000",
        comments: "99",
        caption: "Hello World",
        hero: "./images/juice.jpg",
        verified: true,
    },
    {
        userName: "Shreejal27",
        time: "3 h",
        profileImg: "./images/juice.jpg",
        likes: "1,000",
        comments: "99",
        caption: "Hello World",
        hero: "./images/juice.jpg",
        verified: false,
    },
    {
        userName: "thebackbencherrs",
        time: "14 m",
        profileImg: "./images/juice.jpg",
        likes: "1,000",
        comments: "99",
        caption: "Hello World",
        hero: "./images/juice.jpg",
        verified: false,
    },
]